### ISSUE TITLE
Low-Fi Design (Wireframe)

### ISSUE THREAD

**Issue by uffelman** [TeaDoan/NewVoca#1]
We need a low-fi design (wireframe) to understand the basic structure and functionality of the app. No time should be spent on colors, fonts, etc. This should be a simple pen-and-paper or vector (Sketch) design of all screens of the app. We'll convert this design into tasks to build each piece of the app. Here's an example of the level of fidelity we need. See example below: 
![mockup](https://user-images.githubusercontent.com/13800562/50493283-575c6a80-09d1-11e9-8f16-b9898547f508.jpeg)

**Comment by TeaDoan** [comment]
Got it. I'm working on it. will send you as soon as I'm done.

**Comment by TeaDoan** [comment]
<img width="1194" alt="screen shot 2018-12-27 at 2 13 43 pm" src="https://user-images.githubusercontent.com/32121635/50496298-b0cd9500-09e3-11e9-87c0-660650cf9bc6.png">

**Comment by TeaDoan** [comment]
Let me know what you think.

**Comment by uffelman** [comment]
Looks like enough for me to turn this into user stories. Thanks!
